# YouTube Data API key
YOUTUBE_API_KEY = ""

# Google Gemini API key
GEMINI_API_KEY = ""

# PostgreSQL Database Configuration
# These values are automatically set by Replit
postgresql_host = "${PGHOST}"
postgresql_port = "${PGPORT}"
postgresql_user = "${PGUSER}"
postgresql_password = "${PGPASSWORD}"
postgresql_database = "${PGDATABASE}"