# YouTube Data API key
YOUTUBE_API_KEY = "AIzaSyBTZGM3gET3Js-8PKFkDzpH9aEC_LR3UnQ"
GEMINI_API_KEY = "AIzaSyA9jdcKB19Hku1jsqJekMT2UbbBYopaCoI"

# PostgreSQL Database Configuration
# These values are automatically set by Replit
postgresql_host = "${PGHOST}"
postgresql_port = "${PGPORT}"
postgresql_user = "${PGUSER}"
postgresql_password = "${PGPASSWORD}"
postgresql_database = "${PGDATABASE}"